version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "12000:3000"
    command: sh -c "npm run dev"
